### ISSUE TITLE
[BUG] React Component Error on Profile

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [riolubruh/YABDP4Nitro#120]
@riolubruh @spinfal I'm always getting a React Component Error on my Profile when I look at my own profile

**Comment by riolubruh** [comment]
I'm currently unable to reproduce the error on my end. Can you send a log of the error or something to help me figure out what's causing it?

**Comment by K3NOXOFFICIAL** [comment]
@riolubruh Yep will do in a sec

**Comment by K3NOXOFFICIAL** [comment]
YABDP4Nitro.plugin.js:410 Uncaught (in promise) TypeError: Cannot assign to read only property 'RESOLUTION_1440' of object '#<Object>'
    at YABDP4Nitro.customVideoSettings (YABDP4Nitro.plugin.js:410:40)
    at YABDP4Nitro.saveAndUpdate (YABDP4Nitro.plugin.js:264:13)
    at Settings.SettingPanel.build.Settings.SettingGroup.append.Settings.Switch.settings.screenSharing (YABDP4Nitro.plugin.js:123:51)
    at SettingPanel.alertListeners (0PluginLibrary.plugin.js:3562:74)
    at SettingPanel.onChange (0PluginLibrary.plugin.js:5122:14)
    at Array.eval (0PluginLibrary.plugin.js:5113:26)
    at SettingGroup.alertListeners (0PluginLibrary.plugin.js:3562:74)
    at SettingGroup.onChange (0PluginLibrary.plugin.js:5037:14)
    at Array.eval (0PluginLibrary.plugin.js:5013:26)
    at Switch.alertListeners (0PluginLibrary.plugin.js:3562:74)
    at Switch.onChange (0PluginLibrary.plugin.js:4865:14)
    at eval (0PluginLibrary.plugin.js:5701:43)
    at eval (0PluginLibrary.plugin.js:5663:19)
    at Object.Me (687d98fc15cc0da30654.js:1754:509)
    at je (687d98fc15cc0da30654.js:1754:663)
    at 687d98fc15cc0da30654.js:1775:416
    at Ur (687d98fc15cc0da30654.js:1775:513)
    at Gr (687d98fc15cc0da30654.js:1775:927)
    at 687d98fc15cc0da30654.js:1781:415
    at cc (687d98fc15cc0da30654.js:1846:267)
    at Le (687d98fc15cc0da30654.js:1753:624)
    at Yr (687d98fc15cc0da30654.js:1777:232)
    at Kt (687d98fc15cc0da30654.js:1760:858)
    at Zt (687d98fc15cc0da30654.js:1760:642)
    at HTMLDivElement.n (4fcc9e466b68d0214943.js:564:241)
customVideoSettings @ YABDP4Nitro.plugin.js:410
saveAndUpdate @ YABDP4Nitro.plugin.js:264
Settings.SettingPanel.build.Settings.SettingGroup.append.Settings.Switch.settings.screenSharing @ YABDP4Nitro.plugin.js:123
alertListeners @ 0PluginLibrary.plugin.js:3562
onChange @ 0PluginLibrary.plugin.js:5122
eval @ 0PluginLibrary.plugin.js:5113
alertListeners @ 0PluginLibrary.plugin.js:3562
onChange @ 0PluginLibrary.plugin.js:5037
eval @ 0PluginLibrary.plugin.js:5013
alertListeners @ 0PluginLibrary.plugin.js:3562
onChange @ 0PluginLibrary.plugin.js:4865
eval @ 0PluginLibrary.plugin.js:5701
eval @ 0PluginLibrary.plugin.js:5663
Me @ 687d98fc15cc0da30654.js:1754
je @ 687d98fc15cc0da30654.js:1754
(anonymous) @ 687d98fc15cc0da30654.js:1775
Ur @ 687d98fc15cc0da30654.js:1775
Gr @ 687d98fc15cc0da30654.js:1775
(anonymous) @ 687d98fc15cc0da30654.js:1781
cc @ 687d98fc15cc0da30654.js:1846
Le @ 687d98fc15cc0da30654.js:1753
Yr @ 687d98fc15cc0da30654.js:1777
Kt @ 687d98fc15cc0da30654.js:1760
Zt @ 687d98fc15cc0da30654.js:1760
n @ 4fcc9e466b68d0214943.js:564

**Comment by riolubruh** [comment]
Any updates on this issue @K3NOXOFFICIAL?

**Comment by K3NOXOFFICIAL** [comment]
@riolubruh I now tried it with the new update and the old version seems like the new version fixed it somehow.
Can confirm tho that it still persists when using the older version from before.

**Comment by riolubruh** [comment]
Huh. Neat.

**Comment by WlSDXM** [comment]
heads up, this is happening once again after new discord update.
