### ISSUE TITLE
ZPL is failing to load in the latest discord version

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#225]
```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598937
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9600911)
    at c (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9601298)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598911)
    at p (https://discord.com/assets/8cd0ebdf4d0e19d304ee.js:1:5901)
    at aA (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:990633)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1045869)
    at ok (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028864)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028730
    at oG (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028738)
    at oD (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1025823)
    at r5 (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:974497)
    at ob (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1026327)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054414
    at ll (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054444)
    at t.render (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

    
`stable 318710 (5b3a6a2) Host 1.0.9157 x64 (50412) Build Override: N/A Windows 10 64-bit (10.0.19045)`

**Comment by riolubruh** [comment]
(not my problem)

**Comment by sephentos** [comment]
Hotfix has been released. No more startup errors :)
Feel free to update your copy of this file in your repo, @riolubruh 

https://github.com/zerebos/BDPluginLibrary/blob/3f321f9a3b21f3829277870068b98673ffd5c869/release/0PluginLibrary.plugin.js
